package com.services.uninunezrni.curriculum.domain.model.enums;

public enum ElementoEIC {
    BIBLIOGRAFIA_EN_SEGUNDA_LENGUA,
    REVISTAS_INDEXADAS_INTERNACIONALES,
    CLASES_EN_SEGUNDA_LENGUA,
    VIDEOCONFERENCIAS_TEMATICAS,
    PROFESOR_INVITADO_ESTRUCTURAL,
    PROFESOR_INVITADO_ALEATORIO,
    MULTICULTURALIDAD,
    PERSPECTIVAS_ESTUDIANTE_INTERCAMBIO,
    RECURSOS_VIRTUALES_INTERNACIONALES,
    VIRTUALIZACION_DE_CONTENIDOS,
    PERSPECTIVAS_COMPARATIVAS_CULTURALES,
    RUTAS_ACADEMICAS_SALIDAS_CAMPO,
    COMPETENCIAS_BLANDAS,
    TRABAJOS_PERSPECTIVA_INTERNACIONAL,
    ASISTENCIA_EVENTOS_INTERNACIONALES,
    EXPERTOS_LOCALES_INTERNACIONALES,
    CURSOS_COMPLEMENTARIOS,
    EVALUACION_DE_TRABAJOS_EXTERNOS,
    ASIGNATURAS_CONTENIDOS_INTERNACIONALES,
    PROYECTOS_DOBLE_TITULACION
}
