package com.services.uninunezrni.curriculum.eicRegistration.domain.model.enums;

public enum ProgramaAcademico {
    ADMINISTRACION_DE_EMPRESAS,
    CONTADURIA_PUBLICA,
    TECNOLOGIA_EN_CONTABILIDAD_SISTEMATIZADA,
    BACTERIOLOGIA,
    ENFERMERIA_BARRANQUILLA,
    ENFERMERIA_CARTAGENA,
    MEDICINA,
    ODONTOLOGIA,
    INSTRUMENTACION_QUIRURGICA,
    TECNOLOGIA_EN_MECANICA_DENTAL,
    TECNOLOGIA_EN_ESTETICA_Y_COSMETOLOGIA,
    TECNOLOGIA_EN_ATENCION_PREHOSPITALARIA,
    DERECHO_CARTAGENA,
    DERECHO_BARRANQUILLA,
    LIC_EN_EDUCACION_INFANTIL,
    INGENIERIA_DE_SISTEMAS,
    TECNOLOGIA_EN_DESARROLLO_DE_SISTEMAS,
    ESPECIALIZACION_EN_EDUCACION_Y_DIVERSIDAD
}
